[package]
name = "unros-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6"
# clap = { version = "4", features = ["derive"] }
chrono = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "tracing", "parking_lot", "signal", "io-util", "time"] }
log = "0.4"
fxhash = { workspace = true }
async-trait = "0.1"
static_assertions = { workspace = true }
bytes = "1"
rand = { version = "0.8", features = ["small_rng"] }
futures = "0.3"
console-subscriber = { version = "0.2", features = ["parking_lot"]}
serde = { version = "1", features = ["derive"] }
tokio-rayon = "2"
anyhow = "1"
# crossbeam = { workspace = true }