[package]
name = "unros-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6"
clap = { version = "4", features = ["derive"] }
humantime = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "tracing", "parking_lot", "signal", "io-util", "time"] }
anyhow = { workspace = true }
serde = { workspace = true }
log = "0.4"
fxhash = { workspace = true }
tokio-rayon = { workspace = true }
async-trait = { workspace = true }
static_assertions = { workspace = true }
bytes = "1"
rand = { version = "0.8", features = ["small_rng"] }
futures = "0.3"
console-subscriber = { version = "0.2", features = ["parking_lot"]}
# crossbeam = { workspace = true }