[package]
name = "unros-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6"
chrono = { workspace = true }
log = "0.4"
tokio = { workspace = true }
fxhash = { workspace = true }
crossbeam = { workspace = true }
rand = { workspace = true }
async-trait = "0.1"
static_assertions = { workspace = true }
bytes = "1"
futures = "0.3"
console-subscriber = { version = "0.2", features = ["parking_lot"]}
serde = { workspace = true }
anyhow = { workspace = true }
video-rs = { version = "0.5", optional = false }
image = { workspace = true, optional = false }
fast_image_resize = { workspace = true }
spin_sleep = { workspace = true }
tokio-rayon = { workspace = true }