[workspace]
members = [
    "unros-core",
    "telemetry",
    "global-msgs",
    "lunabot",
    "drive",
    "camera",
    "apriltag",
    # If you do not have the RealSense SDK, remove the realsense member
    "realsense",
    "positioning",
    "serial",
    "navigator",
    "rig", "tools",
]
resolver = "2"

[workspace.dependencies]
fxhash = "0.2"
static_assertions = "1"
image = "0.24"
ordered-float = "4"
nalgebra = { version = "0.32", features = ["serde-serialize"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
crossbeam = "0.8"
quaternion-core = { git = "https://github.com/manglemix/quaternion-core.git", features = ["serde-serialize"]}
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }