[workspace]
members = [
    "unros-core",
    "telemetry",
    "global-msgs",
    "lunabot",
    "drive",
    "camera",
    "apriltag",
    "apriltag-test",
    # If you do not have the RealSense SDK, remove the realsense member
    "realsense",
    "positioning",
    "serial",
    "navigator",
    "rig", "tools",
]
resolver = "2"

[workspace.dependencies]
fxhash = "0.2"
static_assertions = "1"
image = "0.24"
ordered-float = "4"
nalgebra = "0.32"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
crossbeam = "0.8"
quaternion-core = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "tracing", "parking_lot", "signal", "io-util", "time", "fs", "io-std", "net"] }
clap = { version = "4", features = ["derive"] }