[workspace]
members = [
    "unros-core",
    "telemetry",
    "global-msgs",
    "lunabot",
    "drive",
    "camera",
    "apriltag",
    "apriltag-test",
    "realsense",
    "positioning",
    "serial", "navigator",
]
resolver = "2"

[workspace.dependencies]
fxhash = "0.2"
static_assertions = "1"
image = "0.24"
ordered-float = "4"
nalgebra = "0.32"
# crossbeam = "0.8"

# realsense-rust = "1"