[workspace]
members = [
    "unros-core",
]

[workspace.dependencies]
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "tracing", "parking-lot"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
console-subscriber = { version = "0.2", features = ["parking_lot"]}
