[workspace]
members = [
    "unros-core",
    "telemetry",
    "global-msgs",
    "lunabot",
    "drive",
    "camera",
    "apriltag",
    "realsense",
    "positioning",
    "serial",
]

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "tracing", "parking_lot", "signal", "io-util", "time"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
console-subscriber = { version = "0.2", features = ["parking_lot"]}
tokio-rayon = "2"
anyhow = "1"
async-trait = "0.1"
fxhash = "0.2"
static_assertions = "1"
image = "0.24"
ordered-float = "4"
# crossbeam = "0.8"

# realsense-rust = "1"