[tasks.build_lunasim]
workspace = false
command = "cargo"
args = ["build", "-p", "lunasim-lib", "--release"]

[tasks.build_lunabase]
workspace = false
command = "cargo"
args = ["build", "-p", "lunabase-lib", "--release"]

[tasks.godot]
workspace = false
dependencies = [
    "build_lunabase",
    "build_lunasim"
]

[tasks.sim]
workspace = false
command = "cargo"
args = ["run", "-p", "lunabot", "--", "sim"]
dependencies = [
    "godot",
]

[tasks.main]
workspace = false
command = "cargo"
args = ["run", "--features=production", "-p", "lunabot", "--", "main"]

[tasks.del-cabinet]
workspace = false
command = "cargo"
args = ["run", "-p", "urobotics-tool", "--", "deletecabinet"]

[tasks.mouser-web]
workspace = false
command = "npm"
cwd = "mouser/mouser-web"
args = ["run", "build"]

[tasks.mouser-host]
workspace = false
command = "cargo"
dependencies = [
    "mouser-web",
]
args = ["run", "-p", "mouser-host"]