[tasks.build_lunasim]
workspace = false
command = "cargo"
args = ["build", "-p", "lunasim-lib", "--release"]

[tasks.build_lunabase]
workspace = false
command = "cargo"
args = ["build", "-p", "lunabase-lib", "--release"]

[tasks.godot]
workspace = false
dependencies = [
    "build_lunabase",
    "build_lunasim"
]

[tasks.sim]
workspace = false
command = "cargo"
args = ["run", "-p", "lunabot", "--", "sim"]
dependencies = [
    "build_lunasim",
]

[tasks.main]
workspace = false
command = "cargo"
args = ["run", "--features=production", "-p", "lunabot", "--", "main"]

[tasks.clean]
workspace = false
command = "cargo"
args = ["run", "-p", "lunabot", "--", "clean"]

[tasks.import_lunabase]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "--import"]

[tasks.lunabase]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "-d"]
dependencies = [
    "build_lunabase",
    "import_lunabase",
]