anchors: 
  - anchor1:
    id: 0x671a
    flag: 1
    coordinates:
      x: 0
      y: 270
      z: 0
  - anchor2:
    id: 0x762a
    flag: 1
    coordinates:
      x: 760
      y: 270
      z: 0
  - anchor3:
    id: 0x672d
    flag: 1
    coordinates:
      x: 1040
      y: 0
      z: 0
  - anchor4:
    id: 0x6733
    flag: 1
    coordinates:
      x: 270
      y: 0
      z: 0
