[package]
name = "apriltag-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camera = { path = "../camera" }
apriltag = { path = "../apriltag" }
unros-core = { path = "../unros-core" }