[package]
name = "lunabot"
version = "0.1.0"
edition = "2021"

[dependencies]
urobotics = { workspace = true, features = [
    "serial",
    "camera",
    "python",
    "app",
    "video",
] }
serde = { workspace = true }
spin_sleep = { workspace = true }
cakap2 = { workspace = true }
anyhow = { workspace = true }
crossbeam = { workspace = true }
common = { path = "../common" }
pathfinding = { path = "../pathfinding" }
nalgebra = { workspace = true }
k = { workspace = true }
# indexmap = "2.2.6"
fxhash = { workspace = true }
recycler = { workspace = true }
bitcode = { workspace = true }
thalassic.workspace = true
gputter.workspace = true
lunabot-ai = { path = "../lunabot-ai" }
vesc_translator.git = "https://github.com/Hydro111/vesc-translator.git"