[package]
name = "lunabot"
version = "0.1.0"
edition = "2021"

[dependencies]
urobotics = { workspace = true, features = ["serial", "camera", "python", "app"]}
bonsai-bt = "0.6.3"
serde = { workspace = true }
spin_sleep = { workspace = true }
cakap = { workspace = true }
anyhow = { workspace = true }
common = { path = "../common" }