[package]
name = "urobotics-py"
version = "0.1.0"
edition = "2021"

[dependencies]
urobotics-core = { workspace = true }
urobotics-app = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }