services:
  lunadev:
    image: ghcr.io/utahrobotics/lunabotics/luna:2024
    tty: true
    pull_policy: always
    working_dir: "/root/lunadev-2024"
    devices:
      - "/dev/serial/by-id/usb-Pozyx_Labs_Pozyx_Virtual_ComPort_in_FS_Mode_367339643436-if00:/dev/ttyACM0"
      # - "/dev/video_paths/:/dev"
    volumes:
      - type: bind
        source: ../
        target: /root/lunadev-2024

