[package]
name = "usb-pluggy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# dependencies for linux only
[target.'cfg(target_os = "linux")'.dependencies]
sudo = "0.6"