[package]
name = "compute-shader"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0"
anyhow = { workspace = true }
bytemuck = { workspace = true }
tokio = { workspace = true }
crossbeam = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
env_logger = "0"