[build]
rustflags = ["--cfg", "tokio_unstable"]

[env]
RUST_BACKTRACE = "1"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "--cfg", "tokio_unstable"]