[python]
packages_to_install = [
    "cv2_enumerate_cameras"
]

[camera]
# identifier = { Index=0 }
identifier = { Name="Logi C270 HD WebCam" }

[main]
target_delta = 0.5
lunabase_address = "10.0.0.45:10600"

[sim]
target_delta = 0.5
lunabase_address = "127.0.0.1:10600"
simulation_command = ["C:\\Program Files (x86)\\Steam\\steamapps\\common\\Godot Engine\\godot.windows.opt.tools.64.exe", "--path", "godot\\lunasim", "-d"]