[package]
name = "urobotics-app"
version = "0.1.0"
edition = "2021"

[dependencies]
# clap = { version = "4.5.4", features = ["cargo"] }
urobotics-core = { workspace = true }
fxhash = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }