[package]
name = "urobotics-app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
urobotics-core = { workspace = true }
fxhash = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }