[package]
name = "lunabase-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { workspace = true }
crossbeam = { workspace = true }
common = { path = "../common" }
cakap = { workspace = true }
tasker = { workspace = true }
log = { workspace = true }
byteable = { workspace = true }