[package]
name = "lunabase-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { workspace = true }
common = { path = "../common" }
cakap2 = { workspace = true }
bitcode = { workspace = true }
tasker.workspace = true
openh264 = { version = "0.6.3", features = ["source"]}
webrtc = { version = "0.12.0" }
axum = { workspace = true }
tokio.workspace = true
k.workspace = true
crossbeam.workspace = true
serde_json = "1.0.133"
# bytes.workspace = true
