[package]
name = "lumpur"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
ctrlc = "3.4.5"
cursive = "0.21"
parking_lot.workspace = true
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19" }
unfmt.workspace = true
