[package]
name = "camera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nokhwa = { version = "0.10", features = ["input-native"] }
unros = { path = "../unros" }
image = { workspace = true }