[package]
name = "camera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unros = { path = "../unros" }
image = { workspace = true }

[target.'cfg(unix)'.dependencies]
eye = "0.5"
