[package]
name = "positioning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eskf = { git = "https://github.com/manglemix/eskf-rs.git" }
unros-core = { path = "../unros-core" }
nalgebra = "0.32"