name: build and release

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: Export Lunabase Windows
    runs-on: windows-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3
      - name: Build Lunabase Lib
        run: cargo make build_lunabase
      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.3-stable
          export-templates: true
      - name: Create Export Directory
        run: mkdir godot/lunabase/lunabase

      - name: Debug - List Directory Structure
        shell: powershell
        run: |
          Get-ChildItem -Path godot -Recurse
          Write-Host "Current directory:"
          Get-Locatio

      - name: Export Lunabase Windows
        run: godot --headless --export-release "Windows Desktop" lunabase/Lunabase.exe
        working-directory: godot/lunabase

      - name: Debug - Check Export Result
        shell: powershell
        run: |
          Write-Host "Checking export directory:"
          Get-ChildItem -Path godot/lunabase -Recurse

      # Alternative archive step with explicit working directory
      - name: Archive Lunabase Windows
        working-directory: ./godot/lunabase
        run: 7z a -tzip ../../lunabase_windows.zip ./lunabase/*

      - name: Debug - Check Zip Contents
        run: 7z l lunabase_windows.zip

      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./lunabase_windows.zip
