name: build and release

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: Export Lunabase Windows
    runs-on: windows-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3
      - run: cargo make build_lunabase
      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.3-stable
          export-templates: true
      - run: godot --headless --export-release "Windows Desktop" lunabase/Lunabase.exe
        working-directory: godot/lunabase
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -tzip lunabase.zip ./godot/lunabase/lunabase
      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            godot/lunabase/lunabase.zip
