name: BuildDockerImages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - 'lunabase/*.dockerfile'
      - 'lunabase/*.sh'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'lunabase/*.dockerfile'
      - 'lunabase/*.sh'

jobs:
  build_amd64:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.0
        with:
          key: docker-amd64

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build AMD64 base
        run: docker build lunabase/ --file lunabase/luna.dockerfile --target base --tag ghcr.io/utahrobotics/lunabotics/base:2024
      
      - name: Push AMD64 base
        run: docker image push ghcr.io/utahrobotics/lunabotics/base:2024
      
      - name: Build AMD64 lunabase
        run: docker build lunabase/ --file lunabase/luna.dockerfile --target lunabase --tag ghcr.io/utahrobotics/lunabotics/lunabase:2024
      
      - name: Push AMD64 lunabase
        run: docker image push ghcr.io/utahrobotics/lunabotics/lunabase:2024
